import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z
    .enum(["development", "test", "production"])
    .default("development"),
  APP_URL: z.url(),
  DATABASE_URL: z.string().min(1),
  DIRECT_DATABASE_URL: z.string().min(1).optional(),
  OPENAI_API_KEY: z.string().min(1),
  OPENAI_MODEL: z.string().min(1).default("gpt-5.4-mini"),
  NEXTAUTH_URL: z.url(),
  NEXTAUTH_SECRET: z.string().min(32),
  EMAIL_FROM: z.string().optional(),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().optional(),
  SMTP_USER: z.string().optional(),
  SMTP_PASSWORD: z.string().optional(),
  SMTP_SECURE: z.enum(["true", "false"]).optional(),
  GOOGLE_DOCS_SERVICE_ACCOUNT_EMAIL: z.string().optional(),
  GOOGLE_DOCS_SERVICE_ACCOUNT_PRIVATE_KEY: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_ID: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_SECRET: z.string().optional(),
  SEED_DEMO_ACCOUNT: z.enum(["true", "false"]).optional(),
  SEED_DEMO_EMAIL: z.email().optional(),
  SEED_DEMO_PASSWORD: z.string().min(8).optional(),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  APP_URL: process.env.APP_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  DIRECT_DATABASE_URL: process.env.DIRECT_DATABASE_URL || undefined,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL: process.env.OPENAI_MODEL,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL ?? process.env.APP_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  EMAIL_FROM: process.env.EMAIL_FROM,
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: process.env.SMTP_PORT,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,
  SMTP_SECURE: process.env.SMTP_SECURE,
  GOOGLE_DOCS_SERVICE_ACCOUNT_EMAIL: process.env.GOOGLE_DOCS_SERVICE_ACCOUNT_EMAIL,
  GOOGLE_DOCS_SERVICE_ACCOUNT_PRIVATE_KEY: process.env.GOOGLE_DOCS_SERVICE_ACCOUNT_PRIVATE_KEY,
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  SEED_DEMO_ACCOUNT: process.env.SEED_DEMO_ACCOUNT,
  SEED_DEMO_EMAIL: process.env.SEED_DEMO_EMAIL,
  SEED_DEMO_PASSWORD: process.env.SEED_DEMO_PASSWORD,
});
